coverage:
  status:
    project: off
    patch: off
component_management:
  individual_components:
    - component_id: package_model
      name: model
      paths: 
        - app/src/main/java/xterminators/spellingbee/model/**
      statuses:
        - type: project
          target: 100%
        - type: patch
