component_management:
  default_rules:
    status:
      project: off
      patch: off
  individual_components:
    - component_id: package_model
      name: model
      paths: 
        - app/src/main/java/xterminators/spellingbee/model/**
      statuses:
        - type: project
          target: 100%
        - type: patch
