/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package xterminators.spellingbee;

import java.io.File;
import java.nio.file.Paths;
import java.util.Arrays;

import xterminators.spellingbee.controller.CLIController;
import xterminators.spellingbee.view.CLIView;
import xterminators.spellingbee.view.GuiView;

public class App {
    public static void main(String[] args) {
        File dictionaryFile = new File(
            Paths.get("src", "main", "resources", "dictionaries", "dictionary_optimized.txt").toString()
        );

        File rootsDictionaryFile = new File(
            Paths.get("src", "main", "resources", "dictionaries", "dictionary_roots.txt").toString()
        );
        
        // Case Insensitive check for --cli in args
        if (Arrays.asList(args).stream().anyMatch(s -> s.equalsIgnoreCase("--cli"))) {
            CLIView cliView = new CLIView();
            CLIController cliController = new CLIController(cliView, dictionaryFile, rootsDictionaryFile);

            cliController.run();
        } else {
            GuiView ui = new GuiView(dictionaryFile, rootsDictionaryFile);
            ui.InitUI();
        }
    }
}
