name: Gradle CI

on:
  pull_request:
    branches:
      - develop
    types: [opened, reopened]
  push:
    branches:
      - '*'

jobs:
  gradle:
    strategy:
        matrix:
          os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ maxtix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 20

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Execute Gradle build
      run: ./gradlew build

    - name: Execute Gradle test
      run: ./gradlew test
